spring:
  datasource:
    url: jdbc:mysql://34.94.103.198:3306/lendly?useSSL=false&serverTimezone=UTC
    username: root
    password: csci201
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  resources:
    static-locations: classpath:/static
  mvc:
    view:
      prefix: /static
      suffix: .html
