spring:
  datasource:
    url: jdbc:mysql:///lendly?cloudSqlInstance=lendly-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&serverTimezone=UTC
    username: root
    password: csci201
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
