spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lendly
    username: neel
    password: kombucha
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
