- name: Build frontend with React
  run: |
    cd frontend
    npm install .
    npm run build
    cp -r build ../backend/src/main/resources/static
- name: Deploy
  run: |
    cd backend
    gcloud app deploy app.yml --quiet