name: Build and Deploy

on:
  push:
    branches:
      - dev_edgar

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build backend with Maven
        run: |
          cd backend
          mvn clean package

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Set up Google Cloud SDK and authenticate
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          project_id: lendly-383321

      - name: Build frontend with React
        run: |
          cd frontend
          npm install .
          npm run build

      - name: Deploy frontend
        run: |
          cd ${{ github.workspace }}/frontend
          gcloud app deploy app.yml --quiet

      - name: Deploy backend
        run: |
          cd ${{ github.workspace }}/backend
          gcloud app deploy app.yml --quiet